openapi: 3.0.0
info:
  title: Physical AI Tutor Chat API
  version: 1.0.0
  description: API contract for the chat functionality between frontend chat widget and backend AI service

paths:
  /chat:
    post:
      summary: Send a message to the AI tutor and receive a response
      description: Processes a user question and returns an AI-generated response with proper formatting. Supports contextual queries with selected text.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: The user's question or message to the AI tutor
                  example: "Explain how this works?"
                context:
                  type: string
                  description: Optional context, such as selected text or current page information
                  example: "Context: ROS 2 nodes communicate using a publish-subscribe model where nodes exchange messages through topics...\n\n```python\nclass MinimalPublisher(Node):\n    def __init__(self):\n        super().__init__('minimal_publisher')\n        self.publisher_ = self.create_publisher(String, 'topic', 10)\n```"
                pageContext:
                  type: string
                  description: Information about the current page/chapter where the query originated
                  example: "Chapter 3: ROS 2 Fundamentals"
      responses:
        '200':
          description: Successful response from the AI tutor
          content:
            application/json:
              schema:
                type: object
                required:
                  - response
                  - timestamp
                properties:
                  response:
                    type: string
                    description: The AI's response, may contain markdown formatting
                    example: "The code you've selected shows how to create a basic publisher node in ROS 2. The `MinimalPublisher` class inherits from `Node`, and creates a publisher that sends `String` messages to the 'topic' topic with a queue size of 10..."
                  timestamp:
                    type: string
                    format: date-time
                    description: The timestamp of the response
                    example: "2025-12-09T10:30:00Z"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message explaining the issue
                    example: "Message field is required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Failed to process the request"

components:
  schemas:
    ChatMessage:
      type: object
      required:
        - message
        - timestamp
        - sender
      properties:
        message:
          type: string
          description: The content of the message
        context:
          type: string
          description: Optional context such as selected text or page information
        timestamp:
          type: string
          format: date-time
          description: When the message was sent
        sender:
          type: string
          enum: [user, ai]
          description: Who sent the message